/**
 * Standardized error codes for API responses
 * These codes help frontend identify specific error types for proper handling
 */

// Authentication & Authorization Errors (AUTH_*)
export const AUTH_NO_TOKEN = 'AUTH_NO_TOKEN';
export const AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN';
export const AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED';
export const AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED';
export const AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS';
export const AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED';
export const AUTH_ACCOUNT_INACTIVE = 'AUTH_ACCOUNT_INACTIVE';
export const AUTH_INSUFFICIENT_PERMISSIONS = 'AUTH_INSUFFICIENT_PERMISSIONS';

// Subscription & Trial Errors (SUB_*)
export const SUB_TRIAL_EXPIRED = 'SUB_TRIAL_EXPIRED';
export const SUB_SUBSCRIPTION_REQUIRED = 'SUB_SUBSCRIPTION_REQUIRED';
export const SUB_MANAGER_SUBSCRIPTION_REQUIRED = 'SUB_MANAGER_SUBSCRIPTION_REQUIRED';
export const SUB_SUBSCRIPTION_INACTIVE = 'SUB_SUBSCRIPTION_INACTIVE';
export const SUB_SUBSCRIPTION_CANCELLED = 'SUB_SUBSCRIPTION_CANCELLED';
export const SUB_PLAN_NOT_FOUND = 'SUB_PLAN_NOT_FOUND';
export const SUB_USAGE_LIMIT_REACHED = 'SUB_USAGE_LIMIT_REACHED';

// Validation Errors (VAL_*)
export const VAL_VALIDATION_ERROR = 'VAL_VALIDATION_ERROR';
export const VAL_INVALID_REQUEST = 'VAL_INVALID_REQUEST';
export const VAL_MISSING_FIELD = 'VAL_MISSING_FIELD';
export const VAL_INVALID_FORMAT = 'VAL_INVALID_FORMAT';
export const VAL_INVALID_EMAIL = 'VAL_INVALID_EMAIL';
export const VAL_INVALID_PASSWORD = 'VAL_INVALID_PASSWORD';
export const VAL_PASSWORD_WEAK = 'VAL_PASSWORD_WEAK';
export const VAL_INVALID_ID = 'VAL_INVALID_ID';
export const VAL_INVALID_DATE = 'VAL_INVALID_DATE';

// Resource Errors (RES_*)
export const RES_NOT_FOUND = 'RES_NOT_FOUND';
export const RES_ALREADY_EXISTS = 'RES_ALREADY_EXISTS';
export const RES_USER_NOT_FOUND = 'RES_USER_NOT_FOUND';
export const RES_PROPERTY_NOT_FOUND = 'RES_PROPERTY_NOT_FOUND';
export const RES_UNIT_NOT_FOUND = 'RES_UNIT_NOT_FOUND';
export const RES_TENANT_NOT_FOUND = 'RES_TENANT_NOT_FOUND';
export const RES_REPORT_NOT_FOUND = 'RES_REPORT_NOT_FOUND';
export const RES_SERVICE_REQUEST_NOT_FOUND = 'RES_SERVICE_REQUEST_NOT_FOUND';
export const RES_JOB_NOT_FOUND = 'RES_JOB_NOT_FOUND';
export const RES_INVITE_NOT_FOUND = 'RES_INVITE_NOT_FOUND';
export const RES_MAINTENANCE_NOT_FOUND = 'RES_MAINTENANCE_NOT_FOUND';
export const RES_INSPECTION_NOT_FOUND = 'RES_INSPECTION_NOT_FOUND';

// Access Control Errors (ACC_*)
export const ACC_ACCESS_DENIED = 'ACC_ACCESS_DENIED';
export const ACC_PROPERTY_ACCESS_DENIED = 'ACC_PROPERTY_ACCESS_DENIED';
export const ACC_UNIT_ACCESS_DENIED = 'ACC_UNIT_ACCESS_DENIED';
export const ACC_ROLE_REQUIRED = 'ACC_ROLE_REQUIRED';
export const ACC_CSRF_TOKEN_INVALID = 'ACC_CSRF_TOKEN_INVALID';

// Database Errors (DB_*)
export const DB_OPERATION_FAILED = 'DB_OPERATION_FAILED';
export const DB_UNIQUE_CONSTRAINT = 'DB_UNIQUE_CONSTRAINT';
export const DB_FOREIGN_KEY_CONSTRAINT = 'DB_FOREIGN_KEY_CONSTRAINT';
export const DB_RELATION_VIOLATION = 'DB_RELATION_VIOLATION';
export const DB_RECORD_NOT_FOUND = 'DB_RECORD_NOT_FOUND';

// File Upload Errors (FILE_*)
export const FILE_NO_FILE_UPLOADED = 'FILE_NO_FILE_UPLOADED';
export const FILE_INVALID_TYPE = 'FILE_INVALID_TYPE';
export const FILE_TOO_LARGE = 'FILE_TOO_LARGE';
export const FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED';
export const FILE_DELETE_FAILED = 'FILE_DELETE_FAILED';

// External Service Errors (EXT_*)
export const EXT_STRIPE_ERROR = 'EXT_STRIPE_ERROR';
export const EXT_STRIPE_NOT_CONFIGURED = 'EXT_STRIPE_NOT_CONFIGURED';
export const EXT_EMAIL_SEND_FAILED = 'EXT_EMAIL_SEND_FAILED';
export const EXT_SERVICE_UNAVAILABLE = 'EXT_SERVICE_UNAVAILABLE';

// Business Logic Errors (BIZ_*)
export const BIZ_INVITE_EXPIRED = 'BIZ_INVITE_EXPIRED';
export const BIZ_INVITE_ALREADY_ACCEPTED = 'BIZ_INVITE_ALREADY_ACCEPTED';
export const BIZ_EMAIL_ALREADY_REGISTERED = 'BIZ_EMAIL_ALREADY_REGISTERED';
export const BIZ_CANNOT_DELETE_SELF = 'BIZ_CANNOT_DELETE_SELF';
export const BIZ_INVALID_STATUS_TRANSITION = 'BIZ_INVALID_STATUS_TRANSITION';
export const BIZ_OPERATION_NOT_ALLOWED = 'BIZ_OPERATION_NOT_ALLOWED';
export const BIZ_SCHEDULING_CONFLICT = 'BIZ_SCHEDULING_CONFLICT';

// General Errors (ERR_*)
export const ERR_INTERNAL_SERVER = 'ERR_INTERNAL_SERVER';
export const ERR_BAD_REQUEST = 'ERR_BAD_REQUEST';
export const ERR_CONFLICT = 'ERR_CONFLICT';
export const ERR_UNKNOWN = 'ERR_UNKNOWN';
